# DO NOT EDIT
# THIS FILE IS AUTOMATICALLY GENERATED - ANY CHANGES WILL BE OVERWRITTEN
#
{% if not helpers.empty('OPNsense.netdefense.settings.enabled') %}
ndagent_enable="YES"
ndagent_config="/usr/local/etc/ndagent.conf"
ndagent_pidfile="/var/run/ndagent.pid"
ndagent_logfile="/var/log/ndagent.log"
{% else %}
ndagent_enable="NO"
{% endif %}