package tasks

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"testing"

	"github.com/netdefense-io/ndagent/internal/opnapi"
)

const capturedManagedRule = "221f3268-097c-440a-8a8f-adbd0d7d3bf9"

// searchRow returns the captured search row with this uuid.
func searchRow(t *testing.T, uuid string) map[string]interface{} {
	t.Helper()
	for _, r := range searchRows26(t) {
		if r["uuid"] == uuid {
			return r
		}
	}
	t.Fatalf("no captured row %s", uuid)
	return nil
}

// TestPortableRule_CapturedManagedRule pulls the managed rule as the lab
// device lists it: a rule from a pulled snippet whose description already
// doubled its template tag, with the grid's display values and alias metadata.
func TestPortableRule_CapturedManagedRule(t *testing.T) {
	got := portableRule(searchRow(t, capturedManagedRule), ruleModel26(t))

	want := map[string]interface{}{
		"uuid":            capturedManagedRule,
		"enabled":         "1",
		"action":          "pass",
		"interface":       "lan,wireguard",
		"direction":       "in",
		"ipprotocol":      "inet",
		"protocol":        "any",
		"source_net":      "SOC_Hosts",
		"destination_net": "any",
		"description":     "Test var 40000 sniptest01",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("portableRule =\n %v\nwant\n %v", got, want)
	}
}

func TestPortableRule_KeepsNonDefaultsAndNamesReferences(t *testing.T) {
	model := ruleModel26(t, withCategories("c1000000-0000-4000-8000-000000000001", "web", "c2000000-0000-4000-8000-000000000002", "dns"))
	row := map[string]interface{}{}
	for _, name := range model.Names() {
		field, _ := model.Field(name)
		row[name] = field.Default
	}
	row["uuid"] = "7179a1de-88f9-428f-a5b7-d4814890be9f"
	row["interface"] = "lan"
	row["log"] = "1"
	row["quick"] = "0"
	row["statetype"] = "sloppy"
	row["categories"] = "c2000000-0000-4000-8000-000000000002,c1000000-0000-4000-8000-000000000001"
	row["overload"] = "221f3268-0000-4000-8000-00000000a001"
	row["sequence"] = "1"
	row["sort_order"] = "400000.0000001"
	row["prio_group"] = "400000"
	row["%action"] = "Pass"
	row["description"] = "Default allow LAN to any rule"

	got := portableRule(row, model)

	for field, want := range map[string]string{
		"log":        "1",
		"quick":      "0",
		"statetype":  "sloppy",
		"categories": "dns,web",
		"overload":   "SOC_Hosts",
	} {
		if got[field] != want {
			t.Errorf("%s = %v, want %q", field, got[field], want)
		}
	}
	for _, dropped := range []string{"sequence", "sort_order", "prio_group", "%action", "tag", "max", "nosync"} {
		if _, ok := got[dropped]; ok {
			t.Errorf("%s should not be pulled", dropped)
		}
	}
	for field, v := range got {
		if _, ok := v.(string); !ok {
			t.Errorf("%s is %T; snippet values are strings", field, v)
		}
	}
}

func TestRefuseNonMVCRule(t *testing.T) {
	rows := searchRows26(t)
	var legacyUser, automatic map[string]interface{}
	for _, r := range rows {
		if legacy, _ := r["legacy"].(bool); !legacy {
			continue
		}
		if _, ok := r["seq"].(float64); ok && legacyUser == nil {
			legacyUser = r
		} else if !ok && automatic == nil {
			automatic = r
		}
	}
	if legacyUser == nil || automatic == nil {
		t.Fatal("the capture should hold a configured legacy rule and a generated one")
	}

	description, _ := legacyUser["description"].(string)
	if err := refuseNonMVCRule(legacyUser); err == nil || err.Error() != `rule "`+description+`" is a legacy rule: migrate it under Firewall > Migration assistant first` {
		t.Errorf("configured legacy rule: err = %v", err)
	}
	if err := refuseNonMVCRule(automatic); err == nil || !strings.Contains(err.Error(), "generated by OPNsense") {
		t.Errorf("generated rule: err = %v", err)
	}
	if err := refuseNonMVCRule(searchRow(t, capturedManagedRule)); err != nil {
		t.Errorf("an MVC rule was refused: %v", err)
	}
}

// TestRulePullRoundTrip: a pulled rule stored as a snippet and synced back to
// the same device is the source rule again, apart from what NetDefense owns:
// the uuid, the sequence and the template tags.
func TestRulePullRoundTrip(t *testing.T) {
	model := ruleModel26(t, withCategories("c1000000-0000-4000-8000-000000000001", "web"))
	source := map[string]interface{}{}
	for _, name := range model.Names() {
		field, _ := model.Field(name)
		source[name] = field.Default
	}
	for k, v := range map[string]string{
		"uuid": "651c4e72-1a2d-494b-b1ed-2a89b26888d6", "sequence": "11", "action": "block", "interface": "lan,wan",
		"protocol": "TCP", "destination_port": "8080", "log": "1", "quick": "0", "statetype": "modulate",
		"categories": "c1000000-0000-4000-8000-000000000001", "overload": "221f3268-0000-4000-8000-00000000a001",
		"max-src-conn": "10", "source_net": "SOC_Hosts", "description": "Block 8080 [nd-template:old]",
	} {
		source[k] = v
	}

	content, err := json.Marshal(portableRule(source, model))
	if err != nil {
		t.Fatal(err)
	}
	rule := desiredRule(t, "pulled", RulePositionPrepend, 1000, string(content), "new")
	body, refusal := buildRuleBody(rule, model, release267)
	if refusal != nil {
		t.Fatalf("the pulled content was refused: %+v", refusal)
	}

	for name, want := range source {
		if ruleContract.skipped(name) || name == "description" {
			continue
		}
		if body[name] != want {
			t.Errorf("%s: synced %q, source %q", name, body[name], want)
		}
	}
	if body["description"] != "Block 8080 [nd-template:new]" {
		t.Errorf("description = %q", body["description"])
	}
}

// TestPullRule_ReadsTheModelAndRefusesLegacy drives pullRule against a device
// stand-in: the lookup by description, then the model.
func TestPullRule_ReadsTheModelAndRefusesLegacy(t *testing.T) {
	rows := searchRows26(t)
	template := ruleTemplate(t)
	mux := http.NewServeMux()
	mux.HandleFunc("/firewall/filter/searchRule", func(w http.ResponseWriter, r *http.Request) {
		var req map[string]interface{}
		_ = json.NewDecoder(r.Body).Decode(&req)
		phrase, _ := req["searchPhrase"].(string)
		var matched []map[string]interface{}
		for _, rw := range rows {
			if d, _ := rw["description"].(string); strings.Contains(strings.ToLower(d), strings.ToLower(phrase)) {
				matched = append(matched, rw)
			}
		}
		_ = json.NewEncoder(w).Encode(opnapi.SearchResponse{Rows: matched, RowCount: len(matched), Total: len(matched)})
	})
	mux.HandleFunc("/firewall/filter/getRule", func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode(map[string]interface{}{"rule": template})
	})
	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)
	client := opnapi.NewClient(srv.URL, "key", "secret", true)

	content, err := pullRule(context.Background(), client, "sniptest01")
	if err != nil {
		t.Fatal(err)
	}
	if content["description"] != "Test var 40000 sniptest01" || content["uuid"] != capturedManagedRule {
		t.Errorf("content = %v", content)
	}

	_, err = pullRule(context.Background(), client, "Default deny / state violation")
	if err == nil || !strings.Contains(err.Error(), "generated by OPNsense") {
		t.Errorf("a generated rule: err = %v, want it refused as generated", err)
	}
}
