package tasks

import (
	"context"
	"fmt"

	"github.com/netdefense-io/ndagent/internal/opnapi"
)

// ruleAlwaysPulled are the fields a pulled rule carries even at their default,
// so the content reads as a rule: what it does, where, and to what.
var ruleAlwaysPulled = map[string]bool{
	"enabled":         true,
	"action":          true,
	"interface":       true,
	"direction":       true,
	"ipprotocol":      true,
	"protocol":        true,
	"source_net":      true,
	"destination_net": true,
	"description":     true,
}

// pullRule searches for a rule by partial description match and returns it as
// portable rule content: what a RULE snippet holds and SYNC applies.
// Returns error if multiple rules match (uniqueness required).
func pullRule(ctx context.Context, client *opnapi.Client, description string) (map[string]interface{}, error) {
	row, err := client.GetRuleByDescription(ctx, description)
	if err != nil || row == nil {
		return nil, err
	}
	if err := refuseNonMVCRule(row); err != nil {
		return nil, err
	}

	model, err := client.GetRuleModel(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to read the rule model: %w", err)
	}
	return portableRule(row, model), nil
}

// refuseNonMVCRule refuses a row that is not a rule of OPNsense's rule model.
// The search lists legacy rules and the rules OPNsense generates too, with the
// interface as a display label ("WAN") that SYNC would refuse.
func refuseNonMVCRule(row map[string]interface{}) error {
	if legacy, _ := row["legacy"].(bool); !legacy {
		return nil
	}
	description, _ := row["description"].(string)
	// A rule from the legacy rule list has its index there; one a plugin or
	// OPNsense itself generates has none.
	if _, configured := row["seq"].(float64); configured {
		return fmt.Errorf("rule %q is a legacy rule: migrate it under Firewall > Migration assistant first", description)
	}
	return fmt.Errorf("rule %q is generated by OPNsense, not configured, and cannot be pulled", description)
}

// portableRule turns a device rule into snippet content (fieldContract.portable),
// naming its categories and overload alias.
func portableRule(row map[string]interface{}, model opnapi.EntityModel) map[string]interface{} {
	return ruleContract.portable(row, model, ruleAlwaysPulled)
}
